version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Password
    volumes:
      - ./docker/postgresql:/var/lib/postgresql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080